name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - DefaultOffsetRestorer/**
    - DefaultOffsetRestorer.sln

jobs:
  build:
    name: DefaultOffsetRestorer
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up environment
      run: ${{ github.workspace }}\.github\workflows\set_up_env.ps1 "${{ github.workspace }}\DefaultOffsetRestorer\manifest.json"

    - name: Fetch Beat Saber Bindings
      run: git clone https://${{ secrets.PRIVATE_GITHUB_TOKEN }}@github.com/nicoco007/BeatSaberBindings --branch v${{ env.GAME_VERSION }} --single-branch '${{ runner.temp }}\BeatSaberBindings\Beat Saber_Data\Managed'

    - name: Download dependencies
      uses: nicoco007/download-beatmods-deps@main
      with:
        manifest: ${{ github.workspace }}\DefaultOffsetRestorer\manifest.json
        path: ${{ runner.temp }}\BeatSaberBindings
        game-version: "1.31.0"

    - name: Add NuGet source
      run: dotnet nuget update source "nicoco007 GitHub Packages" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
  
    - name: Build Debug
      run: dotnet publish ${{ github.workspace }}\DefaultOffsetRestorer\DefaultOffsetRestorer.csproj -c Debug -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Debug
      uses: actions/upload-artifact@v3
      with:
        name: DefaultOffsetRestorer-${{ env.ZIP_VERSION }}-DEBUG
        path: ${{ github.workspace }}\DefaultOffsetRestorer\bin\Debug\publish

    - name: Build Release
      run: dotnet publish ${{ github.workspace }}\DefaultOffsetRestorer\DefaultOffsetRestorer.csproj -c Release -p:BeatSaberDir=${{ runner.temp }}\BeatSaberBindings

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: DefaultOffsetRestorer-${{ env.ZIP_VERSION }}-RELEASE
        path: ${{ github.workspace }}\DefaultOffsetRestorer\bin\Release\publish
